name: Deploy Next.js Site to GitHub Pages

on:
  push:
    branches:
      - main # Set this to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Use whatever Node.js version your project requires

      - name: Install Dependencies
        run: npm install

      - name: Build 
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out # The output directory of next export
          keep_files: true # Set to true to keep files that are not in the publish_dir
          # Optional: Enable this if you're deploying to a custom domain
          # cname: yourcustomdomain.com
